export const test = [
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
  { name: "jhon" },
  { name: "harry" },
  { name: "mick" },
];

export default test;
